apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
data:
  log-format: |
    '$remote_addr - [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_client_id"'

